### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.utils.training_utils'`

### ISSUE THREAD

**Issue by tobimichigan** [evilsocket/ergo#10]
tried running 
1. ergo help 

and 

2. ergo example 

and the following error occurs:
`Traceback (most recent call last):
  File "/home/hg/anaconda3/bin/ergo", line 22, in <module>
    from ergo.actions.create import action_create
  File "/home/hg/anaconda3/lib/python3.7/site-packages/ergo/actions/create.py", line 6, in <module>
    from ergo.project import Project
  File "/home/hg/anaconda3/lib/python3.7/site-packages/ergo/project.py", line 13, in <module>
    from keras.utils.training_utils import multi_gpu_model
ModuleNotFoundError: No module named 'keras.utils.training_utils'`

any clues?

**Comment by tux-mind** [comment]
`sed -i s/training_utils/multi_gpu_utils/ ergo/project.py`

@evilsocket you might want to freeze the versions in `requirements.txt` :)

**Comment by TheBuccaneer** [comment]
Actually I couldn't find a solution for this problem. Uninstalled keras and installed it again directly from github. As far as I can tell, it's copying the file, but ergo still doesn't find it. In my case (I don't need gpu support) it works to comment out the import line in project.py.

**Comment by nicochidt** [comment]
@TheBuccaneer, try doing this: 

```
pip uninstall keras 
pip install keras==2.2.4
```

If that solves the problem, we can modify the requirements.txt.

**Comment by SebRut** [comment]
@nicochidt that seems to work for me

**Comment by dpmendes** [comment]
> `sed -i s/training_utils/multi_gpu_utils/ ergo/project.py`
> 
> @evilsocket you might want to freeze the versions in `requirements.txt` :)

That would help a lot! I'm having trouble with the '.shape' parameter of the 'pe-malicious' column...

**Comment by nicochidt** [comment]
keras, tensorflow and sklearn versions freezed.
