### ISSUE TITLE
Ergo command doesn't print anything

### ISSUE THREAD

**Issue by Bedotech** [evilsocket/ergo#4]
When i type `ergo` no error and no output is return, the exit code remain 0, i have try to put a python debugger line inside the `ergo` script installed under bin, but the debugger doesn't start.

I use Python `3.7.3` installed with `pyenv`, i think the problem is on `pyenv` side but i have posted this issue here because is the first time i have this problem, other packages are not effected i can execute other packages binary regularly.

**Comment by evilsocket** [comment]
not sure how to help you if you decide to use an alternative installation method that's not mentioned in the doc ... if you follow the instructions, everything works as expected:

![Schermata da 2019-05-20 12-47-47](https://user-images.githubusercontent.com/86922/58016272-7e8d1300-7afd-11e9-869c-c8c709176904.png)

**Comment by kscarlett** [comment]
I'm having the same issue. I think your current installation instructions assume an environment set up for machine learning already.

I installed it [as specified here](https://github.com/evilsocket/ergo#installing), and `ergo help` didn't return anything. After some debugging, I found out it was missing Keras and Tensorflow.
After installing these, I was at least getting tracebacks for the following missing modules: pandas, sklearn, terminaltables and flask.

After installing all these one by one with pip, `ergo help` returns correctly.

**Comment by evilsocket** [comment]
mmm,. it'd look like `sudo pip3 install ergo-ai` doesn't install the dependencies, this is weird, i need to investigate

**Comment by iukea1** [comment]
@evilsocket  Help me senapi
I think I am having the same issue 
```
my-MacBook-Pro:ergo my$ ergo help
Traceback (most recent call last):
  File "/usr/local/bin/ergo", line 4, in <module>
    __import__('pkg_resources').run_script('ergo-ai==1.12.2', 'ergo')
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/ergo' not found in metadata at '/usr/local/lib/python3.7/site-packages/ergo_ai-1.12.2.dist-info'
```

Any suggestions?
