### ISSUE TITLE
Convert model to tflite

### ISSUE THREAD

**Issue by Tigzy** [evilsocket/ergo#7]
Hello, 
I'm not sure it's an issue, probably just a question.
I'm trying to convert my model to tflite format to be used on clients (still the one from pe-av)

I've converted to Tensoflow using ergo to-tf 
Then, I'm using tflite_convert (with the input/output arrays gotten from a script found here and there, extracted from the pb file) but I have an error: 

![image](https://user-images.githubusercontent.com/9531438/58582296-b4df3680-8251-11e9-8130-e95f8f3f8ab8.png)

I'm wondering, is that TF .pb format something compatible with tflite ? 
How do I know for sure that I'm using the correct input/output arrays, is there a way to extract that from ergo model ?

**Comment by nicochidt** [comment]
This seems to be more a tensorflow question than an ergo question. 

Keep in mind that TF-lite doesn't support all operations supported by tensorflow. That seems to be the problem based on the `Only Merge supported` stated in the error you've posted. 

Check if the TF model generated by ergo works in TF, if it does, it's not an ergo problem. 

I'm closing this.

**Comment by Tigzy** [comment]
If by "loads in TF" you mean the classification works, then yes it works. 
I thought maybe there's a way to know the input/output tensors created by Ergo ? Or is it just a regular TF problem ? Thanks,
